### ISSUE TITLE
Selected tasker doesn’t fill its level

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#18]
![image](https://github.com/ozmen54/tasker/assets/93757827/f7158cab-1dd2-4f18-b093-e5deea99795b)
![image](https://github.com/ozmen54/tasker/assets/93757827/9cff9adf-2ba6-45b3-9f9f-06f14b6691ff)

**Comment by ozmen54** [comment]
This must be fixed. Would you please check this again?

**Comment by eskhas** [comment]
I only selected tasker and didn't choose a level on top of the screen, clicked assign button. Still wants me to select a level for the tasker.

**Comment by ozmen54** [comment]
In the Task Assign form, a possible tasker minimum level must be selected
first, and then the task date-time, the duration.
The level in the form is important because tasks can be in different
difficulty levels. Managers do not want to assign complex tasks to a novice
tasker.
The "select" button filters taskers below the given level, equal and above
level taskers are coming as a list to choose from.
It is required in this way.
---
Prof.Dr. Ahmet Özmen
Department of Software Engineering
Sakarya University
+90 (264) 295 6984


Muhammet Ali ÇABUK ***@***.***>, 10 Şub 2024 Cmt, 00:10
tarihinde şunu yazdı:
