### ISSUE TITLE
Inputs gets deleted in user update panel

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#20]
I try to add a new photo to a tasker, and when i save it without giving password, it needs the photo again.
![image](https://github.com/ozmen54/tasker/assets/93757827/2ea95e1e-f08a-4cb0-a5a9-7f5da075122b)
![image](https://github.com/ozmen54/tasker/assets/93757827/695b59d7-38ff-4efc-bbfb-fd6f724f52ae)

**Comment by ozmen54** [comment]
Fixed before, would you please test it again?

**Comment by eskhas** [comment]
I tried the same test on that and still it needed from me to upload the photo again.

**Comment by ozmen54** [comment]
I did not see the problem.
Steps:
1) Press the "Chose file" button.
2) Select image file.
3) Enter password.
4) Then click "Save" button

The image will be updated. I can make the password come to the update form
and update form items without entering the password. Do you think it will
be safe?

I think if a user wants to update something on the profile, he/she must
re-enter the password. Otherwise, in unattended cases, somebody can
make changes.

---
Prof.Dr. Ahmet Özmen
Department of Software Engineering
Sakarya University
+90 (264) 295 6984


Muhammet Ali ÇABUK ***@***.***>, 9 Şub 2024 Cum, 23:46
tarihinde şunu yazdı:

**Comment by eskhas** [comment]
In this case, I meant that when there is a missing part in our user update panel, it shouldn't require the things that we already filled like photo in this situation, it should just need the empty parts and not the ones we filled before.

**Comment by ozmen54** [comment]
Update form shows whatever was recorded in the DB about a user. Some parts
are allowed to be empty when a new user is added, then those parts can be
filled by means of update. For example, for a quick registration admin may
want to skip adding a photo of a tasker, and then later he may want to add
that. As you observed some parts are necessary and guarded with server side
validation. You can not proceed (or register a new user) without providing
them.

I guess the password must also be brought to the update form. If the admin
writes something different there then the password will be updated as well,
which will be a problem for the taskers. We are not allowing the taskers to
enter their passwords yet. This is a small scale application, and only
the admin does that via "add user" or "update user".
Thanks.
---
Prof.Dr. Ahmet Özmen
Department of Software Engineering
Sakarya University
+90 (264) 295 6984


Muhammet Ali ÇABUK ***@***.***>, 10 Şub 2024 Cmt, 14:08
tarihinde şunu yazdı:
